logging.file: logs/application.log
logging:
  level:
    org:
      springframework:
        web: DEBUG
      hibernate: ERROR
spring:
  datasource:
    url: jdbc:h2:file:./database/parking
    driver-class-name: org.h2.Driver
    username: sa
    database-platform: org.hibernate.dialect.H2Dialect
  jpa:
    show-sql: true
  h2:
    console:
      enabled: true